### ISSUE TITLE
Facing os path error in windows 10

### ISSUE THREAD

**Issue by sabitahmad** [Taipoon/NeoUdeler#3]
Traceback (most recent call last):
  File "F:\Courses\NeoUdeler\main.py", line 58, in <module>
    main()
  File "F:\Courses\NeoUdeler\main.py", line 54, in main
    course.download_all_contents('.')
  File "F:\Courses\NeoUdeler\neoudeler.py", line 364, in download_all_contents
    os.mkdir(save_dir)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '.\\20230812_Tailwind CSS 3 | Learn By Building Multiple Projects A-Z - Kazi Ariyan'

**Comment by Taipoon** [comment]
@sabitahmad 
Thank you for the issue report.

By default, NeoUdeler sets the course title as the name of the directory where the videos are saved. However, in the Windows operating system, special characters such as <, >, :, ", /, \, |, ?, * cannot be used, leading to the error. To circumvent this issue, I've made changes to replace any disallowed characters in the directory name with `` (empty character).

I'm a MacOS user, so this issue was an oversight on my part.

**Comment by sabitahmad** [comment]
All right. I will test it now.

**Comment by sabitahmad** [comment]
Its fixed now downloading perfectly.
